travis:
  secure:
    BINSTAR_TOKEN: Y1U9j2q2aA6sTvZdkxGshh0hWFslrBM0XjOVY5qzDOhKUPaLU8KRB85AcfCjFKdjLgsq31I5UFwv3Vv12Stb4XN5hdHhUQ4pRxwGYaK/o6JjBQWBOPgBlkLZeZ09J6QOOi6JaYjp2Mkhld0Fg0gNKPtZcFjIqWjdBIC9PJJ7Se0T1K5F371fJSIkmv84jA8vi9IHhm264O3e3+kU8EqaRemUWXLwqCsxNXAVjNVF1tSlU0qm0mDNib8xYKjgo151UAJoN+T67AXwVWQ7MAta/90xei3MrrS3rwKPniNrWCBsPEwLeBFKrCIHGfeHt6XBRkPKOXt+6GTagr/zVy5ryU14UdfWRyUEoApnr5Xcf9/zkD9ptt7v/i9b/dnwsB56V9x2jqNTKxpknWzzpUOi2gEItsSevQW08ELqPpI6cRNwsK57kGPTAHmwTvXyHZxwwqjAK+mwjmMf79aiv7PJ1i3EbMhcxVlLuyLdIAi2jd46L0vDgm1JLMjtcNVftPoo3cd8FVRo9WDNwu4S643J2F5vSOjcEcANRvmjbUtXYcDkMCkHlQ7/OjeM5jZDKdCgLKh3iKya/km9W8yZN8fDejGHKUrIskRBJSWEvXoXrmJMuXagABEM4ANKZPtRn5pKDLzRFBm1n7CRbP5becKu3X63BYujj8QlsgCTHz30odU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
