travis:
  secure:
    BINSTAR_TOKEN: Ocs7PXglz7EF+ifCVFDmw7JO7z+0/EvH0fF2nV+QiAQIwQKZ3/RK1STh04bihJSafGQMjpW7KUglllvLyBbL2SBKXlLwA+vfI0zGUmgXxaxF2/Wp/iCUNx1+s9au8SNp1tkCvbDrTh7yJPFpyrVTLtGFPp7BdUhEtDSdZ+sE9NxhXOAIKV8tfB3zaO3X8x8eeLRc/96fH8n3KG8/gRStpc0RcmjmotPb4dTGQST1usEXRZ6ImY3HOtvN9sIY80+wU/xxvwUTYjpUXcAcAU6CE7dmapX2I/nUqntqhWn0AB5ARV5yDqHxjHXmfYI6x9Fc8L9fp1xcuJBvrkw/70HtjODsZRvjFReb8T08aY7cYjvzQfcnlzSOylzjTCSBDDlsZ+HF+pXiZHf2stGroGXV2T71rRgKnM7AQ58IZDaXGVbXfPGAZNzluapoU07e0On8vPo9EsBHDXrv9pQzX7uEBQbNMAGTcVzre/F3SeWj8q8FYKEHpp2ZSMvYlxqz6q+bAuGl2WulbX9ZL3tul/IfdRaogVH2fteCorhtxnr/o6G6mOUOFDTEsYQW5EiSe9xKmtqHS6HserTU+TpJ+Js0yKQJeawcGWuRpSa2fMaAd7Zx4mwJjniUwr6FYR6iExCxfs66+cOZFf+5bRoYJR4k86cn+tcpvLrTxIODm6Msq5U=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
